// vue-app/src/App.vue
<template>
  <div class="App">
    <div class="header">
      <span>My Vue App</span>
      <input id="meetingId" type="text" placeholder="Room id" />
      <button @click="JoinMeeting()">Join</button>
    </div>
    <div style="display: flex; flex: 1">
      <app-builder> </app-builder>
    </div>
  </div>
</template>

<script>
import "./app.css";
import AppBuilderWebSdk from "@appbuilder/web";
// eslint-disable-next-line
import React from "react";
// To prevent react getting removed in dead code elimination step;
React.createElement("div");

let unsubCreateEvent = () => {};
let unsubReadyToJoinEvent = () => {};
let unsubJoinEvent = () => {};
let unsubLeaveEvent = () => {};

const myCustomization = AppBuilderWebSdk.createCustomization({
  // components:{
  //     videocall: () => <div>Hi</div>
  //   }
});
AppBuilderWebSdk.customize(myCustomization);

export default {
  name: "App",
  methods: {
    JoinMeeting() {
      AppBuilderWebSdk.join(document.getElementById("meetingId").value);
    },
  },
  mounted() {
    unsubCreateEvent = AppBuilderWebSdk.on(
      "create",
      (hostMeetingId, attendeeMeetingId, pstnNumber) => {
        console.log("Vue Host App: Meeting created with", {
          hostMeetingId,
          attendeeMeetingId,
          pstnNumber,
        });
      }
    );
    unsubReadyToJoinEvent = AppBuilderWebSdk.on(
      "ready-to-join",
      (meetingTitle, deviceList) => {
        console.log("Vue Host App: precall with", {
          meetingTitle,
          deviceList,
        });
      }
    );
    unsubJoinEvent = AppBuilderWebSdk.on(
      "join",
      (meetingTitle, deviceList, isHost) => {
        console.log("Vue Host App: Meeting joined with", {
          meetingTitle,
          deviceList,
          isHost,
        });
      }
    );
    unsubLeaveEvent = AppBuilderWebSdk.on("leave", () => {
      console.log("Vue Host App: Meeting left");
    });
  },
  unmounted() {
    unsubCreateEvent();
    unsubReadyToJoinEvent();
    unsubJoinEvent();
    unsubLeaveEvent();
  },
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
</style>

// react-app/src/App.js
import React, { useEffect } from "react";
import "./app.css";
import AppBuilderReactSdk from "@appbuilder/react";

function App() {
  useEffect(() => {
    const myCustomization = AppBuilderReactSdk.createCustomization({
      // components:{
      //     videocall: () => <div>Hi</div>
      //   }
    });

    AppBuilderReactSdk.customize(myCustomization);

    const unsubCreateEvent = AppBuilderReactSdk.on(
      "create",
      (hostMeetingId, attendeeMeetingId, pstnNumber) => {
        console.log("React Host App: Meeting created with", {
          hostMeetingId,
          attendeeMeetingId,
          pstnNumber,
        });
      }
    );
    const unsubReadyToJoinEvent = AppBuilderReactSdk.on(
      "ready-to-join",
      (meetingTitle, deviceList) => {
        console.log("React Host App: precall with", {
          meetingTitle,
          deviceList,
        });
      }
    );
    const unsubJoinEvent = AppBuilderReactSdk.on(
      "join",
      (meetingTitle, deviceList, isHost) => {
        console.log("React Host App: joined with", {
          meetingTitle,
          deviceList,
          isHost,
        });
      }
    );
    const unsubLeaveEvent = AppBuilderReactSdk.on("leave", () => {
      console.log("React Host App: left");
    });
    return () => {
      unsubCreateEvent();
      unsubReadyToJoinEvent();
      unsubJoinEvent();
      unsubLeaveEvent();
    };
  }, []);

  const joinMeeting = () => {
    AppBuilderReactSdk.join(document.getElementById("meetingId").value);
  };

  return (
    <div className="App">
      <div className="header">
        <span>My React App</span>
        <input id="meetingId" type="text" placeholder="Room id"></input>
        <button onClick={joinMeeting}>Join</button>
      </div>
      <div style={{ display: "flex", flex: 1 }}>
        <AppBuilderReactSdk.View />
      </div>
    </div>
  );
}

export default App;
